# 连接数据库的配置参数
server:
  port: 9900

# 连接数据库的配置参数
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csmall_ups?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

#配置日志  log-impl:日志实现
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置Mapper路径
  mapper-locations: classpath:mapper/*xml


# 日志的显示级别默认info(根包尽量这样写,若简写会扩大不必要的范围,多写比较麻烦)
logging:
  level:
    cn.tedu.anhuicsmall.product: trace